[package]

name = "twilio"
version = "0.1.2"
description = "Rust bindings for the Twilio API"
readme = "README.md"
repository = "https://github.com/neil-lobracco/twilio-rs"
license = "MIT"
authors = ["Neil LoBracco <neil.lobracco@gmail.com>", "Lance Carlson <lancecarlson@gmail.com>"]
keywords = ["twilio","rust"]

[dependencies]
hyper = "^0.10"
hyper-native-tls = "^0.3"
mime = "^0.2"
rust-crypto = "^0.2"
url="^1.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
base64 = "0.6"

[dev-dependencies]
dotenv = "0.10.1"
